#!/usr/bin/env bash
# Copyright (c) 2016-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the license file.

# Travis CI configuration.
# References:
#   1. https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js:
  - "6"
  - "4"
cache: yarn
before_script:
  - yarn global add gulp
  - yarn install
script: gulp --harmony lint
